services:
  - type: web
    name: luxbot
    env: python
    buildCommand: ""
    startCommand: bash start.sh
    envVars:
      - key: TOKEN
        value: 7808348593:AAHhzFVKLLYm2ROsXsvgBdXII45W2di76Fc
